// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoParts.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoParts.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260818055439_AddOrderIsPaid")]
    partial class AddOrderIsPaid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoParts.Domain.Models.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostCode")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeliveryAddressess");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.DeliveryStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeliveryStatuses");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.IncomeMoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("IncomeMotos");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<short>("OperationId")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Qty")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SellCost")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("UnitCost")
                        .HasColumnType("numeric");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("UserId");

                    b.HasIndex("OperationId", "CreatedAt");

                    b.HasIndex("ZipId", "CreatedAt");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Mark")
                        .IsUnique();

                    b.ToTable("MotoMarks");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MarkId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarkId");

                    b.ToTable("MotoModels");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("SeriesName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MotoSeries");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Operation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("TypeId")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.OperationType", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OperationTypes");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("CountOrdered")
                        .HasColumnType("integer");

                    b.Property<short?>("DeliveryStatusId")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("boolean");

                    b.Property<short?>("OperationId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("OrderDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("PriceCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("SellCost")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("DeliveryStatusId");

                    b.HasIndex("OperationId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZipId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("PartNum")
                        .IsUnique();

                    b.ToTable("PartNumbers");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumberApplicability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ModelId")
                        .HasColumnType("integer");

                    b.Property<int>("PartNumId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartNumId", "ModelId")
                        .IsUnique();

                    b.ToTable("PartNumberApplicabilities");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumberSeriesApplicability", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PartNumId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SeriesId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("PartNumId", "SeriesId")
                        .IsUnique();

                    b.ToTable("PartNumberSeriesApplicabilities");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PriceHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("NewCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OldCost")
                        .HasColumnType("numeric");

                    b.Property<short>("OperationId")
                        .HasColumnType("smallint");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OperationId");

                    b.HasIndex("UserId");

                    b.HasIndex("ZipId", "CreatedAt");

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Stored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZipId")
                        .IsUnique();

                    b.ToTable("Stored");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistrar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSender")
                        .HasColumnType("boolean");

                    b.Property<string>("OAuthProvider")
                        .HasColumnType("text");

                    b.Property<string>("OAuthSubject")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.UserDraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FormKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "FormKey")
                        .IsUnique();

                    b.ToTable("UserDrafts");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Zip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<decimal>("IncomeCost")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("IncomeDate")
                        .HasColumnType("date");

                    b.Property<Guid>("IncomeMotoId")
                        .HasColumnType("uuid");

                    b.Property<int>("PartNumId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("SellCost")
                        .HasColumnType("numeric");

                    b.Property<short?>("Year")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IncomeMotoId");

                    b.HasIndex("PartNumId");

                    b.ToTable("Zips");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.ZipGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZipGroups");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.ZipPhoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZipId");

                    b.ToTable("ZipPhotos");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.DeliveryAddress", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.IncomeMoto", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany("IncomeMotos")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Log", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.Operation", "Operation")
                        .WithMany("Logs")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.Order", "Order")
                        .WithMany("Logs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Domain.Models.Zip", "Zip")
                        .WithMany("Logs")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Operation");

                    b.Navigation("Order");

                    b.Navigation("User");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoModel", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.MotoMark", "Mark")
                        .WithMany("MotoModels")
                        .HasForeignKey("MarkId");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Operation", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.OperationType", "Type")
                        .WithMany("Operations")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Type");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Order", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.DeliveryAddress", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.DeliveryStatus", "DeliveryStatus")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Domain.Models.Operation", "Operation")
                        .WithMany("Orders")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.Zip", "Zip")
                        .WithMany("Orders")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("DeliveryStatus");

                    b.Navigation("Operation");

                    b.Navigation("User");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumber", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.ZipGroup", "Group")
                        .WithMany("PartNumbers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumberApplicability", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.MotoModel", "Model")
                        .WithMany("Applicability")
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.PartNumber", "PartNumber")
                        .WithMany("Applicability")
                        .HasForeignKey("PartNumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Model");

                    b.Navigation("PartNumber");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumberSeriesApplicability", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.PartNumber", "PartNumber")
                        .WithMany("SeriesApplicability")
                        .HasForeignKey("PartNumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.MotoSeries", "Series")
                        .WithMany("Applicability")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PartNumber");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PriceHistory", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.Operation", "Operation")
                        .WithMany("PriceHistory")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.Zip", "Zip")
                        .WithMany("PriceHistory")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operation");

                    b.Navigation("User");

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Stored", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.Zip", "Zip")
                        .WithOne("Stored")
                        .HasForeignKey("MotoParts.Domain.Models.Stored", "ZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.UserDraft", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Zip", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.IncomeMoto", "IncomeMoto")
                        .WithMany("Zips")
                        .HasForeignKey("IncomeMotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Domain.Models.PartNumber", "PartNumber")
                        .WithMany("Zips")
                        .HasForeignKey("PartNumId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncomeMoto");

                    b.Navigation("PartNumber");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.ZipPhoto", b =>
                {
                    b.HasOne("MotoParts.Domain.Models.Zip", "Zip")
                        .WithMany("Photos")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.DeliveryAddress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.DeliveryStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.IncomeMoto", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoMark", b =>
                {
                    b.Navigation("MotoModels");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoModel", b =>
                {
                    b.Navigation("Applicability");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.MotoSeries", b =>
                {
                    b.Navigation("Applicability");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Operation", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Orders");

                    b.Navigation("PriceHistory");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.OperationType", b =>
                {
                    b.Navigation("Operations");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Order", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.PartNumber", b =>
                {
                    b.Navigation("Applicability");

                    b.Navigation("SeriesApplicability");

                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.User", b =>
                {
                    b.Navigation("DeliveryAddresses");

                    b.Navigation("IncomeMotos");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.Zip", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Orders");

                    b.Navigation("Photos");

                    b.Navigation("PriceHistory");

                    b.Navigation("Stored");
                });

            modelBuilder.Entity("MotoParts.Domain.Models.ZipGroup", b =>
                {
                    b.Navigation("PartNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
