// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoParts.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoParts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260727124014_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAdress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeliveryAdressess");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryStatus", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DeliveryStatuses");
                });

            modelBuilder.Entity("MotoParts.Api.Models.IncomeMoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IncomeMotos");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Mark")
                        .IsUnique();

                    b.ToTable("MotoMarks");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MarkId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarkId");

                    b.ToTable("MotoModels");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Operation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short?>("Type")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdressId")
                        .HasColumnType("integer");

                    b.Property<int>("CountOrdered")
                        .HasColumnType("integer");

                    b.Property<short?>("DeliveryStatusId")
                        .HasColumnType("smallint");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NomenclatureId")
                        .HasColumnType("uuid");

                    b.Property<short?>("OperationTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("OrderDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SellCost")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdressId");

                    b.HasIndex("DeliveryStatusId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OperationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.PartNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartNum")
                        .IsUnique();

                    b.ToTable("PartNumbers");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Stored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZipId");

                    b.ToTable("Stored");
                });

            modelBuilder.Entity("MotoParts.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistrar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSender")
                        .HasColumnType("boolean");

                    b.Property<string>("OAuthProvider")
                        .HasColumnType("text");

                    b.Property<string>("OAuthSubject")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IncomeCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IncomeMotoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MarkId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PartNumId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Year")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IncomeMotoId");

                    b.HasIndex("MarkId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartNumId");

                    b.ToTable("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.ZipGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZipGroups");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAdress", b =>
                {
                    b.HasOne("MotoParts.Api.Models.User", "User")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Log", b =>
                {
                    b.HasOne("MotoParts.Api.Models.Order", "Order")
                        .WithMany("Logs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.HasOne("MotoParts.Api.Models.MotoMark", "Mark")
                        .WithMany("MotoModels")
                        .HasForeignKey("MarkId");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.HasOne("MotoParts.Api.Models.DeliveryAdress", "Adress")
                        .WithMany("Orders")
                        .HasForeignKey("AdressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.DeliveryStatus", "DeliveryStatus")
                        .WithMany("Orders")
                        .HasForeignKey("DeliveryStatusId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Api.Models.Zip", "Nomenclature")
                        .WithMany("Orders")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.Operation", "OperationType")
                        .WithMany("Orders")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Api.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adress");

                    b.Navigation("DeliveryStatus");

                    b.Navigation("Nomenclature");

                    b.Navigation("OperationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Stored", b =>
                {
                    b.HasOne("MotoParts.Api.Models.Zip", "Zip")
                        .WithMany("StoredItems")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.HasOne("MotoParts.Api.Models.ZipGroup", "Group")
                        .WithMany("Zips")
                        .HasForeignKey("GroupId");

                    b.HasOne("MotoParts.Api.Models.IncomeMoto", "IncomeMoto")
                        .WithMany("Zips")
                        .HasForeignKey("IncomeMotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.MotoMark", "Mark")
                        .WithMany("Zips")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Api.Models.MotoModel", "Model")
                        .WithMany("Zips")
                        .HasForeignKey("ModelId");

                    b.HasOne("MotoParts.Api.Models.PartNumber", "PartNumber")
                        .WithMany("Zips")
                        .HasForeignKey("PartNumId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("IncomeMoto");

                    b.Navigation("Mark");

                    b.Navigation("Model");

                    b.Navigation("PartNumber");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAdress", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryStatus", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.IncomeMoto", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoMark", b =>
                {
                    b.Navigation("MotoModels");

                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Operation", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("MotoParts.Api.Models.PartNumber", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.User", b =>
                {
                    b.Navigation("DeliveryAddresses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("StoredItems");
                });

            modelBuilder.Entity("MotoParts.Api.Models.ZipGroup", b =>
                {
                    b.Navigation("Zips");
                });
#pragma warning restore 612, 618
        }
    }
}
