// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MotoParts.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MotoParts.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DeliveryAdressess");
                });

            modelBuilder.Entity("MotoParts.Api.Models.IncomeMoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IncomeMotos");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Mark")
                        .IsUnique();

                    b.ToTable("MotoMarks");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("MarkId")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MarkId");

                    b.ToTable("MotoModels");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Movement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("CountOrdered")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Discount")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("NomenclatureId")
                        .HasColumnType("uuid");

                    b.Property<short?>("OperationTypeId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("OrderDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("SellCost")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OperationTypeId");

                    b.ToTable("Movements");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Operation", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<short?>("Type")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Operations");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("CountOrdered")
                        .HasColumnType("integer");

                    b.Property<Guid?>("NomenclatureId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OrderDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("MotoParts.Api.Models.PartNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PartNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PartNum")
                        .IsUnique();

                    b.ToTable("PartNumbers");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YooKassaPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Stored", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<Guid>("ZipId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZipId");

                    b.ToTable("Stored");
                });

            modelBuilder.Entity("MotoParts.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FIO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRegistrar")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSender")
                        .HasColumnType("boolean");

                    b.Property<string>("OAuthProvider")
                        .HasColumnType("text");

                    b.Property<string>("OAuthSubject")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordResetTokenHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IncomeCost")
                        .HasColumnType("numeric");

                    b.Property<Guid>("IncomeMotoId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MarkId")
                        .HasColumnType("integer");

                    b.Property<int?>("ModelId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PartNumberId")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("Year")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("IncomeMotoId");

                    b.HasIndex("MarkId");

                    b.HasIndex("ModelId");

                    b.HasIndex("PartNumberId");

                    b.ToTable("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.ZipGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ZipGroups");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAddress", b =>
                {
                    b.HasOne("MotoParts.Api.Models.User", "User")
                        .WithMany("DeliveryAddresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.HasOne("MotoParts.Api.Models.MotoMark", "Mark")
                        .WithMany("MotoModels")
                        .HasForeignKey("MarkId");

                    b.Navigation("Mark");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Movement", b =>
                {
                    b.HasOne("MotoParts.Api.Models.DeliveryAddress", "Address")
                        .WithMany("Movements")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.Zip", "Nomenclature")
                        .WithMany("Movements")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Api.Models.Operation", "OperationType")
                        .WithMany("Movements")
                        .HasForeignKey("OperationTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Address");

                    b.Navigation("Nomenclature");

                    b.Navigation("OperationType");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.HasOne("MotoParts.Api.Models.DeliveryAddress", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.Zip", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId");

                    b.Navigation("Address");

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Payment", b =>
                {
                    b.HasOne("MotoParts.Api.Models.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("MotoParts.Api.Models.Payment", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Stored", b =>
                {
                    b.HasOne("MotoParts.Api.Models.Zip", "Zip")
                        .WithMany("StoredItems")
                        .HasForeignKey("ZipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zip");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.HasOne("MotoParts.Api.Models.ZipGroup", "Group")
                        .WithMany("Zips")
                        .HasForeignKey("GroupId");

                    b.HasOne("MotoParts.Api.Models.IncomeMoto", "IncomeMoto")
                        .WithMany("Zips")
                        .HasForeignKey("IncomeMotoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MotoParts.Api.Models.MotoMark", "Mark")
                        .WithMany("Zips")
                        .HasForeignKey("MarkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MotoParts.Api.Models.MotoModel", "Model")
                        .WithMany("Zips")
                        .HasForeignKey("ModelId");

                    b.HasOne("MotoParts.Api.Models.PartNumber", "PartNumber")
                        .WithMany("Zips")
                        .HasForeignKey("PartNumberId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Group");

                    b.Navigation("IncomeMoto");

                    b.Navigation("Mark");

                    b.Navigation("Model");

                    b.Navigation("PartNumber");
                });

            modelBuilder.Entity("MotoParts.Api.Models.DeliveryAddress", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("MotoParts.Api.Models.IncomeMoto", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoMark", b =>
                {
                    b.Navigation("MotoModels");

                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.MotoModel", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Operation", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Order", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("MotoParts.Api.Models.PartNumber", b =>
                {
                    b.Navigation("Zips");
                });

            modelBuilder.Entity("MotoParts.Api.Models.User", b =>
                {
                    b.Navigation("DeliveryAddresses");
                });

            modelBuilder.Entity("MotoParts.Api.Models.Zip", b =>
                {
                    b.Navigation("Movements");

                    b.Navigation("StoredItems");
                });

            modelBuilder.Entity("MotoParts.Api.Models.ZipGroup", b =>
                {
                    b.Navigation("Zips");
                });
#pragma warning restore 612, 618
        }
    }
}
